# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'IOSExampleOC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSExampleOC
  # pod 'VeryOauthSDK', :path => '../../ios'
  pod 'VeryOauthSDK', '1.0.2'

  target 'IOSExampleOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSExampleOCUITests' do
    # Pods for testing
  end

end
