name: iOS Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Validate Podspec
        run: pod spec lint ios/VeryOauthSDK.podspec --allow-warnings

      - name: Push to CocoaPods
        run: pod trunk push ios/VeryOauthSDK.podspec --allow-warnings
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOA_PODS_TRUNK_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## VeryOauthSDK iOS v${{ github.ref_name }}

            ### Features
            - OAuth 2.0 authentication
            - Dual authentication modes (ASWebAuthenticationSession / WKWebView)
            - Camera permission support
            - Modern Swift API

            ### Installation
            ```ruby
            pod 'VeryOauthSDK'
            ```

            Or via Swift Package Manager:
            ```
            https://github.com/veroslabs/very-oauth-sdk.git
            ```
          draft: false
          prerelease: false
